sudo: required
services:
  - docker

before_install:
  - docker build -t akaunowen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akaunowen/react-test npm test

after_success:
  - docker build -t akaunowen/multic-client ./client
  - docker build -t akaunowen/multic-nginx ./nginx
  - docker build -t akaunowen/multic-server ./server
  - docker build -t akaunowen/multic-worker ./worker
  # v- Login to the docker CLI, variables defined in TRAVIS-CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push akaunowen/multic-client
  - docker push akaunowen/multic-nginx
  - docker push akaunowen/multic-server
  - docker push akaunowen/multic-worker

#AWS Elastic Beanstalk config

# deploy:
#     provider: elasticbeanstalk
#     region: <yourRegion_SubDomainFromYourEB_URL>
#     app: multic-docker
#     env: MulticDocker-env
#     bucket_name: "elasticbeanstalk-us-west-2-321132321(AWS services S3 and find the bucket you are currently in)"
#     bucket_path: docker-multi
#     on:
#       branch: master
#     access_key_id: 
#       secure: $AWS_ACCESS_KEY
#     secret_access_key: 
#       secure: $AWS_SECRET_KEY

#/AWS Elastic Beanstalk config